language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source
  - export PATH=../vendor/bin:$PATH
  # start a web server on port 8080, run in the background; wait for initialization
  - php -S 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  - cd testapp
  - behat -fprogress --strict
